management:
    security:
        roles: ADMIN
    context-path: /management

spring:
    application:
        name: robotstore
    jackson:
        serialization.write_dates_as_timestamps: false
    mvc:
        favicon:
            enabled: false
security:
    basic:
        enabled: false
    oauth2:
        resource:
            filter-order: 3

server:
    session:
        cookie:
            http-only: true

jhipster:
    swagger:
        default-include-pattern: /api/.*
        title: robotstore API
        description: robotstore API documentation
        version: 0.0.1
        terms-of-service-url:
        contact-name:
        contact-url:
        contact-email:
        license:
        license-url:

application:
